
%% UNIVERSITY OF PISA
% Computer Science Department
% M.Sc. Computer Science, Artificial Intelligence

%% AUTHOR: IRENE PISANI
% email: i.pisani1@studenti.unipi.it
% matricola: 560104
% date: September 23

%% COMPUTATIONAL NEUROSCIENCE 22/23 - LABORATORY 2.2

% [ COMPLETED ] Assignment 1: Small Image Dataset
% [ No ] Bonus Track Assignment # 1 – Synthetic data
% [ No ] Bonus Track Assignment # 2 – How much can you remember?

%% Assignment 1: Small Image Dataset

% For solving these assignments run the main script:
    % hopfieldMain()
        % PARAMETERS: No input parameter are required. 
        % DESCRIPTION: Load original data and perform the storage phase of
        % the hopfield network with them. Then perform the retrieval phase
        % of the hopfield network with the distorted version of the
        % original vectors. Expploits hopfieldNetwork() and hopfieldPrturbation()
        % OUTPUT: the figure generated by hopfieldPlot()

% Other scripts or functions exploited in this assignments are:
    % hopfieldPerturbation()
    % hopfieldNetwork()
    % hopfieldPlot()
     
%% Function for plots generation

% hopfieldPlot()
    % PARAMETER:
        % history: history of state after each state update
        % energy: sequence of energy values obtained during retrieval phase
        % one element correspond to a single state update. 
        % overlap: sequence of overlap values obtained during retrieval
        % phase - one element correspond to a single state update. 
        % optVector: the optmal correspinding memory vector
        % imgTitle: title for saving the generated images 

    % DESCRIPTION: this function plot energy function, overlaps function
    % over time and show the reconstructed image. It additionally compute
    % the MSE bewteen the the reconstructed image and the optmal
    % corresponding memory. 
    % OUTPUT
        % 1) plot of energy functino over time
        % 2) plot of overlaps function over time
        % 3) show reconstructed image and associated MSE

function hopfieldPlot (history, energy, overlap, optVector,imgTitle)

%%%%%%% 1° Plot

% Energy function over time
figure;
plot(energy);
title("Energy function over time ");
xlabel("Time")
ylabel("Energy function value")
saveas(gcf, 'Results/distorted_' + imgTitle + '_energy', 'jpg')

%%%%%%% 2° Plot 

% Overlap for each training patterns over time
plot(overlap');
xlabel("Time")
ylabel("Overlap function value")
title("Overlaps function over time");
legend("Pattern 0", "Pattern 1", "Pattern 2");
saveas(gcf, 'Results/distorted_' + imgTitle + '_overlap', 'jpg')

%%%%%%% 3° Plot 

% Plot reconstruced image
imagesc(reshape(history(:, end), 32, 32));
% Measure of discrepancy: Mean Squared Error with the optimal corresponding
% memory vector
%mse = ( sum(optVector - history(:, end))^2 ) / 1024;
mse = immse(optVector, history(:, end));
title("Image reconstruction - MSE  = " + mse);
saveas(gcf, "Results/distorted_" + imgTitle + "_reconstructed", 'jpg')

end